### ISSUE TITLE
Package rename raises exception

### ISSUE THREAD

**Issue by sebastianconcept** [amber-smalltalk/amber-attic#1]
`renamePackage: packageName to: newName ` is raising a DNU:
`a SmalltalkImage does not understand #at:`

**Comment by herby** [comment]
Which class contains the `renamePackage:to:`?

**Comment by sebastianconcept** [comment]
SmalltalkImage

**Comment by herby** [comment]
Then it does not belong here.

**Comment by sebastianconcept** [comment]
What about the rest of the `package` category in `SmalltalkImage`?

Where those 6 methods belong?

**Comment by herby** [comment]
??? There, in the SmalltalkImage.

This issue does not belong here.

Sebastian Sastre wrote:

**Comment by sebastianconcept** [comment]
It was discovered using the IDE that's why is here.

Fixing wherever it belongs should fix this too. 

Until that's proven, it's an issue here too.

Opening dependent issue: https://github.com/amber-smalltalk/amber/issues/1134

**Comment by herby** [comment]
This is not a legacy issue per se, closing.
